// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6BcHqF_ETs37E7f2Nx_ecs2qOgA_fwtw',
    appId: '1:188778400352:web:6f1344646d5789f7085105',
    messagingSenderId: '188778400352',
    projectId: 'latestjhcapp',
    authDomain: 'latestjhcapp.firebaseapp.com',
    databaseURL: 'https://latestjhcapp-default-rtdb.firebaseio.com',
    storageBucket: 'latestjhcapp.appspot.com',
    measurementId: 'G-YD1ER8KMSD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8rIaBSL6oLMgA95CepMU9kBQZYFRJ0aU',
    appId: '1:188778400352:android:25bec576486963e9085105',
    messagingSenderId: '188778400352',
    projectId: 'latestjhcapp',
    databaseURL: 'https://latestjhcapp-default-rtdb.firebaseio.com',
    storageBucket: 'latestjhcapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwFaWv-lNdou8wLXawhvAXOzYRu153Aok',
    appId: '1:188778400352:ios:f4145831a68f310d085105',
    messagingSenderId: '188778400352',
    projectId: 'latestjhcapp',
    databaseURL: 'https://latestjhcapp-default-rtdb.firebaseio.com',
    storageBucket: 'latestjhcapp.appspot.com',
    iosBundleId: 'com.jhc.jhc_app',
  );
}
